version: '3.7'

services:

  estoque:
    image: estoque
    container_name: estoque
    restart: always
    pull_policy: build
    build:
          context: estoqueService
          dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - seller-network
    depends_on:
      - mysql
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  produto:
    image: produto
    container_name: produto
    restart: always
    pull_policy: build
    build:
          context: produtoservice
          dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - seller-network
    depends_on:
      - mysql
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      
  endereco:
    image: endereco
    container_name: endereco
    restart: always
    pull_policy: build
    build:
          context: enderecoService
          dockerfile: Dockerfile
    ports:
      - "8004:8004"
    networks:
      - seller-network
    depends_on:
      - mysql
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  venda:
    image: venda
    container_name: venda
    restart: always
    pull_policy: build
    build:
          context: vendaService
          dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - seller-network
    depends_on:
      - mysql
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  naming-server:
    image: nameserver
    container_name: nameserver
    restart: always
    build:
          context: nameserver
          dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - seller-network
  
  api-gateway:
    image: gateway
    container_name: gateway
    restart: always
    pull_policy: build
    ports:
      - "8008:8008"
    networks:
      - seller-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  integrador:
    image: integrador
    container_name: integrador
    restart: always
    build:
          context: nameserver
          dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - seller-network
    depends_on:
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  zipkin-server:
    image: openzipkin/zipkin:2.23
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - seller-network
  mysql:
    image: mysql
    container_name: f_mysql
    restart: always
    pull_policy: build
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - '3306:3306'

networks:
  seller-network: